/*  -------------------------------------
	-- DDL : Data Definition Language
	-- BASE DE DONNEES : H2
	-- SCHEMA OR CATALOG :  
	-------------------------------------
*/

/* 	---------------------------
	-- Scripts de Suppressions 
	---------------------------
*/ 

-- Suppression des tables : T_CATEGORIES, T_CATEGORIES_T_PRODUCTS, T_PRODUCTS
DROP TABLE IF EXISTS T_CATEGORIES CASCADE; 
DROP TABLE IF EXISTS T_CATEGORIES_T_PRODUCTS CASCADE;
DROP TABLE IF EXISTS T_PRODUCTS CASCADE;

/*  ----------------------------------------
	-- Scripts de Création des tables 
	---------------------------------------
*/
-- Création de la table : T_CATEGORIES
CREATE TABLE T_CATEGORIES (
	ID BIGINT NOT NULL,
	CATEGORY_TYPE VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	ENABLED BOOLEAN NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	OPTLOCK INTEGER NOT NULL,
	PRIMARY KEY (ID)
);

-- Création de la table d'association : T_CATEGORIES_T_PRODUCTS
CREATE TABLE T_CATEGORIES_T_PRODUCTS (
	CATEGORY_ID BIGINT NOT NULL,
	PRODUCTS_ID BIGINT NOT NULL,
	PRIMARY KEY (CATEGORY_ID, PRODUCTS_ID)
);

-- Création de la table : T_PRODUCTS    
CREATE TABLE T_PRODUCTS (
	ID BIGINT NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	IMAGE_URL VARCHAR(255) NOT NULL,	
	IS_ACTIVE BOOLEAN NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	PRICE DECIMAL(19,2) NOT NULL,
	QUANTITY BIGINT NOT NULL,
	UNIT_PRICE DECIMAL(19,2) NOT NULL,
	OPTLOCK INTEGER NOT NULL,
	PRIMARY KEY (ID)
); 

-- Contrainte unicité de la colonne : PRODUCTS_ID
ALTER TABLE T_CATEGORIES_T_PRODUCTS 
	ADD CONSTRAINT UK_40p0vt4lvwv479gxy15u63x38 unique (PRODUCTS_ID);

-- Contrainte de la clé étrangère :PRODUCTS_ID dans la table d'association T_CATEGORIES_T_PRODUCTS
ALTER TABLE T_CATEGORIES_T_PRODUCTS 
	ADD CONSTRAINT FKprbvgp7usy4j4cu30t5rkjrl4 
		FOREIGN KEY (PRODUCTS_ID) 
		REFERENCES T_PRODUCTS (ID); 

-- Contrainte de la clé étrangère :CATEGORY_ID dans la table d'association T_CATEGORIES_T_PRODUCTS
ALTER TABLE T_CATEGORIES_T_PRODUCTS 
	ADD CONSTRAINT FK7oh5h90freuloi32a476qa5hk 
		FOREIGN KEY (CATEGORY_ID) 
		REFERENCES T_CATEGORIES (ID);
