/*  ---------------------------------------
	-- DDL : Data Definition Language
	-- BASE DE DONNEES : POSTGRESQL 
	-- SCHEMA OR CATALOG : JWTAUTHWEB
	---------------------------------------
*/

-- Création de la table : T_CATEGORIES
CREATE TABLE IF NOT EXISTS T_CATEGORIES (
	ID INT8 NOT NULL AUTO_INCREMENT,
	CATEGORY_TYPE VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	ENABLED BOOLEAN NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	OPTLOCK INT4 NOT NULL,
	PRIMARY KEY (ID)
);

-- Création de la table d'association : T_CATEGORIES_T_PRODUCTS
CREATE TABLE IF NOT EXISTS T_CATEGORIES_T_PRODUCTS (
	CATEGORY_ID INT8 NOT NULL,
	PRODUCTS_ID INT8 NOT NULL,
	PRIMARY KEY (CATEGORY_ID, PRODUCTS_ID)
);  

-- Création de la table : T_PRODUCTS
CREATE TABLE IF NOT EXISTS T_PRODUCTS (
	ID INT8 NOT NULL AUTO_INCREMENT,
	DESCRIPTION VARCHAR(255) NOT NULL,
	IS_ACTIVE BOOLEAN NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	PRICE NUMERIC(19, 2) NOT NULL,
	QUANTITY int8 NOT NULL,
	UNIT_PRICE NUMERIC(19, 2) NOT NULL,
	OPTLOCK INT4 NOT NULL,
	IMAGE_URL VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

-- Contrainte unicité de la colonne : PRODUCTS_ID
ALTER TABLE T_CATEGORIES_T_PRODUCTS 
	ADD CONSTRAINT UK_40p0vt4lvwv479gxy15u63x38 unique (PRODUCTS_ID);

-- Contrainte de la clé étrangère :PRODUCTS_ID dans la table d'association T_CATEGORIES_T_PRODUCTS
ALTER TABLE T_CATEGORIES_T_PRODUCTS 
	ADD CONSTRAINT FKprbvgp7usy4j4cu30t5rkjrl4 
		FOREIGN KEY (PRODUCTS_ID) 
		REFERENCES T_PRODUCTS (ID); 

-- Contrainte de la clé étrangère :CATEGORY_ID dans la table d'association T_CATEGORIES_T_PRODUCTS
ALTER TABLE T_CATEGORIES_T_PRODUCTS 
	ADD CONSTRAINT FK7oh5h90freuloi32a476qa5hk 
		FOREIGN KEY (CATEGORY_ID) 
		REFERENCES T_CATEGORIES(ID);
