/*  -------------------------------------
	-- DDL : Data Definition Language
	-- BASE DE DONNEES : MARIADB
	-- SCHEMA OR CATALOG : JWTAUTHWEB 
	-------------------------------------
*/

-- Initialisation de la séquence pour les tables T_CATEGORIES et T_PRODUCTS
INSERT INTO HIBERNATE_SEQUENCE VALUES (1);
INSERT INTO HIBERNATE_SEQUENCE VALUES (1);

-- Création de la table : T_CATEGORIES
CREATE TABLE IF NOT EXISTS T_CATEGORIES (
	ID BIGINT(20) NOT NULL,
	CATEGORY_TYPE VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	ENABLED BIT NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	OPTLOCK INT(11) NOT NULL,
	PRIMARY KEY (ID)
) engine=MyISAM;

-- Création de la table d'association : T_CATEGORIES_T_PRODUCTS
CREATE TABLE IF NOT EXISTS T_CATEGORIES_T_PRODUCTS (
	CATEGORY_ID BIGINT(20) NOT NULL,
	PRODUCTS_ID BIGINT(20) NOT NULL,
	PRIMARY KEY (CATEGORY_ID, PRODUCTS_ID)
) engine=MyISAM;

-- Création de la table : T_PRODUCTS 
CREATE TABLE IF NOT EXISTS T_PRODUCTS (
	ID BIGINT(20) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	IMAGE_URL VARCHAR(255) NOT NULL,
	IS_ACTIVE BIT NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	PRICE DECIMAL(19,2) NOT NULL,
	QUANTITY BIGINT(20) NOT NULL,
	UNIT_PRICE DECIMAL(19,2) NOT NULL,
	OPTLOCK INT(11) NOT NULL,
	PRIMARY KEY (ID)
) engine=MyISAM;

-- Contrainte unicité de la colonne : PRODUCTS_ID
ALTER TABLE T_CATEGORIES_T_PRODUCTS 
	ADD CONSTRAINT UK_40p0vt4lvwv479gxy15u63x38 unique (PRODUCTS_ID);

-- Contrainte de la clé étrangère :PRODUCTS_ID dans la table d'association T_CATEGORIES_T_PRODUCTS
ALTER TABLE T_CATEGORIES_T_PRODUCTS 
	ADD CONSTRAINT FKprbvgp7usy4j4cu30t5rkjrl4 
		FOREIGN KEY (PRODUCTS_ID) 
		REFERENCES T_PRODUCTS (ID); 

-- Contrainte de la clé étrangère :CATEGORY_ID dans la table d'association T_CATEGORIES_T_PRODUCTS
ALTER TABLE T_CATEGORIES_T_PRODUCTS 
	ADD CONSTRAINT FK7oh5h90freuloi32a476qa5hk 
		FOREIGN KEY (CATEGORY_ID) 
		REFERENCES T_CATEGORIES (ID);