create sequence hibernate_sequence start with 1 increment by 1
create table t_categories (id bigint not null, category_type varchar(255) not null, description varchar(255) not null, enabled boolean not null, name varchar(255) not null, optlock integer not null, primary key (id))
create table t_categories_products (category_id bigint not null, products_id bigint not null, primary key (category_id, products_id))
create table t_images (id bigint not null, image_url varchar(255) not null, optlock integer not null, primary key (id))
create table t_products (id bigint generated by default as identity, description varchar(255) not null, is_active boolean not null, name varchar(255) not null, price decimal(19,2) not null, quantity bigint not null, unit_price decimal(19,2) not null, optlock integer not null, image_id bigint, primary key (id))
create table t_users (id bigint not null, account_expired boolean not null, account_locked boolean not null, created_time timestamp, credentials_expired boolean not null, email varchar(254) not null, enabled boolean not null, user_password varchar(60) not null, updated_time timestamp, user_name varchar(80) not null, optlock integer not null, primary key (id))
create table user_roles (user_id bigint not null, roles integer)
alter table t_categories_products add constraint UK_aq6dtkh1h9dm9vh0snymjg5e9 unique (products_id)
alter table t_users add constraint UK_1f8qpknpngd98342v0j2ceadc unique (email)
alter table t_users add constraint UK_5ebsdi5h725fqsiarxvgl1j43 unique (user_name)
alter table t_categories_products add constraint FKb6tkcg2hi2rquca4wc3n3k89f foreign key (products_id) references t_products
alter table t_categories_products add constraint FK1hom8ht9j0anfjll4hjf52fkx foreign key (category_id) references t_categories
alter table t_products add constraint FK3m42c7b7e0xlr2dykgutqb8a2 foreign key (image_id) references t_images
alter table user_roles add constraint FKfpmqjl35c9jym3tpu09y3hyqq foreign key (user_id) references t_users
